sudo: false
language: java
  - oraclejdk8
services:
  - mysql
  - redis-server
cache:
  directories:
  - $HOME/.m2
  - $HOME/.jdk
install: true
before_script:
  - mysql -e 'create database myapp_test;'
script:
  - ./mvnw clean compile cobertura:cobertura
after_success:
  - ./mvnw coveralls:report
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.SONATYPE_USERNAME}</username><password>\${env.SONATYPE_PASSWORD}</password></server></servers></settings>" > ~/settings.xml
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      ./mvnw deploy --settings ~/settings.xml  -DskipTests;
    fi
  - if [[ "$TRAVIS_BRANCH" == "releases" ]]; then
      ./mvnw release:prepare release:perform --settings ~/settings.xml  -DskipTests -Darguments="-Dmaven.test.skip=true -DskipTests";
    fi

