cache:
  directories:
  - $HOME/.m2
  - $HOME/.jdk
sudo: false
env:
  global:
  - JDKW=https://raw.githubusercontent.com/vjkoskela/jdk-wrapper/master/jdk-wrapper.sh
  - JDKW_VERSION=8u65
  - JDKW_BUILD=b17
services:
  - mysql
  - redis-server
install: true
before_script:
  - mysql -e 'create database myapp_test;'
script:
  - curl -s ${JDKW} | bash /dev/stdin ./mvnw clean compile
after_success:
  - curl -s ${JDKW} | bash /dev/stdin ./mvnw coveralls:report
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.SONATYPE_USERNAME}</username><password>\${env.SONATYPE_PASSWORD}</password></server></servers></settings>" > ~/settings.xml
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      curl -s ${JDKW} | bash /dev/stdin ./mvnw deploy --settings ~/settings.xml  -DskipTests;
    fi
  - if [[ "$TRAVIS_BRANCH" == "releases" ]]; then
      curl -s ${JDKW} | bash /dev/stdin ./mvnw release:prepare release:perform --settings ~/settings.xml  -DskipTests -Darguments="-Dmaven.test.skip=true -DskipTests";
    fi

