sudo: false
language: java
jdk:
  - openjdk7
services:
  - mysql
  - redis-server
cache:
  directories:
  - $HOME/.m2
install: true
before_script:
  - mysql -e 'create database myapp_test;'
#  - gpg --import beryllium.key
script:
  - mvn install cobertura:cobertura
after_success:
  - mvn coveralls:report
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      mvn deploy --settings ~/settings.xml  -DskipTests;
    fi
  - if [ \( -n "${TRAVIS_TAG}" \) -a  "${TRAVIS_PULL_REQUEST}" = "false" ]; then mvn deploy; fi;

